# Generated by Django 4.1.5 on 2023-02-13 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.PositiveSmallIntegerField()),
                ('cabecera', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.PositiveSmallIntegerField()),
                ('nombre', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.PositiveSmallIntegerField()),
                ('nombre', models.TextField(max_length=150)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'URBANO CONCENTRADO'), (2, 'URBANO(A)'), (3, 'MIXTO'), (4, 'RURAL'), (5, 'RURAL DISPERSO')])),
                ('cabecera', models.PositiveSmallIntegerField(choices=[(1, 'CAPITAL DEL ESTADO'), (2, 'CABECERA DISTRITAL'), (3, 'CABECERA MUNICIPAL'), (4, 'CABECERA SECCIONAL')], null=True)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.PositiveSmallIntegerField()),
                ('nombre', models.TextField()),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.entidad')),
            ],
            options={
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Pusinex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.localidad')),
            ],
            options={
                'verbose_name': 'PUSINEX',
                'verbose_name_plural': 'PUSINEXs',
                'get_latest_by': 'f_actual',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.PositiveSmallIntegerField()),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'URBANO CONCENTRADO'), (2, 'URBANO(A)'), (3, 'MIXTO'), (4, 'RURAL'), (5, 'RURAL DISPERSO')])),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.distrito')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.municipio')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_act', models.DateField()),
                ('hojas', models.PositiveSmallIntegerField()),
                ('observaciones', models.TextField()),
                ('archivo', models.FileField(upload_to='')),
                ('pusinex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.pusinex')),
            ],
        ),
        migrations.AddField(
            model_name='pusinex',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.seccion'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.municipio'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.entidad'),
        ),
    ]
