# Generated by Django 4.1.5 on 2023-02-28 18:44

import control.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localidad',
            options={'ordering': ['municipio__municipio', 'localidad'], 'verbose_name': 'Localidad', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['municipio'], 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterModelOptions(
            name='revision',
            options={'get_latest_by': 'f_act'},
        ),
        migrations.AddField(
            model_name='revision',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revision',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='user',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='revision',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=control.models.pusinex_file),
        ),
        migrations.AlterField(
            model_name='revision',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
