# Generated by Django 4.1.5 on 2023-01-04 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='entidad',
            field=models.PositiveSmallIntegerField(choices=[(29, 'TLAXCALA')]),
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.PositiveSmallIntegerField(choices=[(29, 'TLAXCALA')])),
                ('distrito', models.PositiveSmallIntegerField(choices=[(1, 'APIZACO'), (2, 'TLAXCALA DE XICOHTENCATL'), (3, 'ZACATELCO')])),
                ('seccion', models.PositiveSmallIntegerField()),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'URBANO CONCENTRADO'), (2, 'URBANO(A)'), (3, 'MIXTO'), (4, 'RURAL'), (5, 'RURAL DISPERSO')])),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.municipio')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
            },
        ),
    ]
