# Generated by Django 4.1.5 on 2023-01-04 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_municipio_entidad_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.PositiveSmallIntegerField(choices=[(29, 'TLAXCALA')], default=29)),
                ('localidad', models.PositiveSmallIntegerField()),
                ('nombre', models.TextField(max_length=150)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'URBANO CONCENTRADO'), (2, 'URBANO(A)'), (3, 'MIXTO'), (4, 'RURAL'), (5, 'RURAL DISPERSO')])),
                ('cabecera', models.PositiveSmallIntegerField(choices=[(1, 'CAPITAL DEL ESTADO'), (2, 'CABECERA DISTRITAL'), (3, 'CABECERA MUNICIPAL'), (4, 'CABECERA SECCIONAL')])),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.municipio')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
            },
        ),
    ]
