# Generated by Django 4.1.5 on 2023-01-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='cabecera',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CAPITAL DEL ESTADO'), (2, 'CABECERA DISTRITAL'), (3, 'CABECERA MUNICIPAL'), (4, 'CABECERA SECCIONAL')], null=True),
        ),
    ]
