# Generated by Django 4.1.5 on 2023-01-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_pusinex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pusinex',
            options={'get_latest_by': 'f_actual', 'verbose_name': 'PUSINEX', 'verbose_name_plural': 'PUSINEXs'},
        ),
        migrations.AlterField(
            model_name='pusinex',
            name='f_actual',
            field=models.DateField(verbose_name='Fecha de Actualización'),
        ),
    ]
