# Generated by Django 4.1.6 on 2023-02-07 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_alter_pusinex_options_alter_pusinex_f_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.PositiveSmallIntegerField()),
                ('nombre', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='entidad',
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='pusinex',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='pusinex',
            name='f_actual',
        ),
        migrations.RemoveField(
            model_name='pusinex',
            name='hojas',
        ),
        migrations.RemoveField(
            model_name='pusinex',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='entidad',
        ),
        migrations.AddField(
            model_name='pusinex',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_act', models.DateField()),
                ('hojas', models.PositiveSmallIntegerField()),
                ('observaciones', models.TextField()),
                ('archivo', models.FileField(upload_to='')),
                ('pusinex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.pusinex')),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.PositiveSmallIntegerField()),
                ('cabecera', models.TextField()),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.entidad')),
            ],
        ),
    ]
